.TH "el_cleanup" "3" " 9 June 2019 (v0.4.1)" "bofc.pl"
.SH NAME
.PP
.B el_cleanup
- cleans all resources allocated by
.BR el_init (3)
and
.BR el_option (3)
calls.
.SH SYNOPSIS
.PP
.BI "#include <embedlog.h>"
.PP
.BI "int el_cleanup(void)"
.br
.BI "int el_ocleanup(struct el_options *" options ")"
.SH DESCRIPTION
.PP
.BR el_cleanup (3)
flushes all remaining buffers and frees any resources allocated through the
life of the library.
After clean up, library calls cannot be used without initialization.
.PP
.BR el_ocleanup (3)
works just the same, but accepts custom
.I options
as argument.
.SH RETURN VALUE
.PP
Functions return 0 upon successful cleanup or -1 on errors.
When -1 was returned no resources were freed, and library functions still can be
used.
.SH ERRORS
.PP
.BR el_cleanup (3)
function cannot fail.
.BR el_ocleanup (3)
may return:
.TP
.B EINVAL
Passed options object is not valid
.SH SEE ALSO
.PP
.BR el_init (3),
.BR el_overview (7),
.BR el_option (3),
.BR el_puts (3),
.BR el_print (3),
.BR el_vprint (3),
.BR el_perror (3),
.BR el_pmemory (3),
.BR el_pmemory_table (3),
.BR el_opmemory_table (3),
.BR el_ooption (3),
.BR el_oputs (3),
.BR el_oprint (3),
.BR el_ovprint (3),
.BR el_operror (3),
.BR el_opmemory (3).
